---
name: eliud_pkg_membership
description: eliud_pkg_membership is a package to provide functionality for membership
  of your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_membership
version: 1.1.7
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core: ^1.1.6
  eliud_core_helpers: ^1.0.0
  eliud_pkg_etc: ^1.1.7
  eliud_pkg_etc_model: ^1.0.0
  eliud_core_main: ^1.0.0
  eliud_pkg_membership_model: ^1.0.0
  eliud_pkg_notifications: ^1.1.6
  eliud_pkg_workflow: ^1.1.6
  eliud_pkg_workflow_model: ^1.0.0
  eliud_core_model: ^1.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  transparent_image: ^2.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/findicons.com/
platforms:
  android: null
  ios: null
  web: null
