---
name: eliud_pkg_membership
description: eliud_pkg_membership is a package to provide functionality for membership
  of your eliud app. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_membership
version: 1.1.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core:                                                                                        # ANDROID IOS             WEB
    path: ../eliud_core
  eliud_pkg_etc:                                                                                     # ANDROID IOS             WEB
    path: ../eliud_pkg_etc
  eliud_pkg_membership_model:                                                                        # ANDROID IOS             WEB
    path: ../eliud_pkg_membership_model
  eliud_pkg_notifications:                                                                           # ANDROID IOS             WEB
    path: ../eliud_pkg_notifications
  eliud_pkg_workflow:                                                                                # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow
  eliud_pkg_workflow_model:                                                                          # ANDROID IOS             WEB
    path: ../eliud_pkg_workflow_model

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/findicons.com/
platforms:
  android: null
  ios: null
  web: null
