name: eliud_pkg_membership
description: Eliud package for membership and stuff
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flushbar: ^1.10.4

  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications

dev_dependencies:
  build_runner: "1.10.2"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/findicons.com/
