name: eliud_pkg_membership
description: Eliud package for membership and stuff
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  eliud_core:
    path: ../eliud_core

  eliud_pkg_workflow:
    path: ../eliud_pkg_workflow

  eliud_pkg_notifications:
    path: ../eliud_pkg_notifications

  eliud_pkg_etc:
    path: ../eliud_pkg_etc

dev_dependencies:
  build_runner: "1.11.5"

  eliud_generator:
    path: ../eliud_generator

flutter:
  uses-material-design: true

  assets:
    - assets/images/findicons.com/
