---
name: eliud_pkg_membership
description: Eliud package for membership and stuff
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_membership
version: 1.0.2+2
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  cloud_firestore: ^4.6.0
  collection: ^1.17.0
  datetime_picker_formfield: ^2.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  intl: ^0.18.1
  meta: ^1.8.0
  transparent_image: ^2.0.0
  eliud_core: ^1.0.19+1
  eliud_pkg_workflow: ^1.0.1+20
  eliud_pkg_notifications: ^1.0.1+20
  eliud_pkg_etc: ^1.0.1+20
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: 1.0.8
flutter:
  uses-material-design: true
  assets:
  - assets/images/findicons.com/
platforms:
  android: null
  ios: null
  web: null
